export interface GeolocationData {
  continent: string
  country: string
  zipCode: string
  accuracyRadius: number
  flag: string
  city: string
  timezone: string
  latitude: number
  countryGeoNameId: number
  gmt: string
  network: string
  currencyName: string
  countryNativeName: string
  stateGeoNameId: number
  phoneCode: string
  state: string
  continentCode: string
  longitude: number
  currencyNamePlural: string
  cityGeoNameId: number
  languages: string
  numOfCities: number
  org: string
  ip: string
  currencySymbol: string
  currencySymbolNative: string
  isEU: string
  countryTLD: string
  countryCapital: string
  metroCode: any
  continentGeoNameId: number
  stateCode: string
  countryISO2: string
  numOfStates: number
  countryISO3: string
  currencyCode: string
  asNo: number
  status: number
}
